beast.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast.c -o beast.lo 
aes_algo_handler.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/aes_algo_handler.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/aes_algo_handler.c -o aes_algo_handler.lo 
des_algo_handler.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/des_algo_handler.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/des_algo_handler.c -o des_algo_handler.lo 
base64_algo_handler.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/base64_algo_handler.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/base64_algo_handler.c -o base64_algo_handler.lo 
beast_mm.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast_mm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast_mm.c -o beast_mm.lo 
spinlock.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/spinlock.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/spinlock.c -o spinlock.lo 
cache.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/cache.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/cache.c -o cache.lo 
beast_log.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast_log.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/beast_log.c -o beast_log.lo 
global_algo_modules.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/global_algo_modules.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/global_algo_modules.c -o global_algo_modules.lo 
header.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/header.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/header.c -o header.lo 
networkcards.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/networkcards.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/networkcards.c -o networkcards.lo 
tmpfile_file_handler.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/tmpfile_file_handler.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/tmpfile_file_handler.c -o tmpfile_file_handler.lo 
pipe_file_handler.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/pipe_file_handler.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/pipe_file_handler.c -o pipe_file_handler.lo 
file_handler_switch.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/file_handler_switch.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/file_handler_switch.c -o file_handler_switch.lo 
shm.lo: /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/shm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/wwwroot/pinche.codems.cn/install_data/php-beast-master $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/wwwroot/pinche.codems.cn/install_data/php-beast-master/shm.c -o shm.lo 
$(phplibdir)/beast.la: ./beast.la
	$(LIBTOOL) --mode=install cp ./beast.la $(phplibdir)

./beast.la: $(shared_objects_beast) $(BEAST_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_beast) $(BEAST_SHARED_LIBADD)

